[project]
name = "python-courseware"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "uvicorn>=0.52.3",
]

[project.optional-dependencies]
courseware = [
  "fastapi",
  "google-genai",
  "huggingface-hub",
  "httpx",
  "instructor[google-genai]",
  "jupyterlab",
  "nbclient",
  "nbformat",
  "numpy",
  "openai",
  "pandas",
  "pydantic",
  "pytest",
  "python-dotenv",
  "requests",
  "scikit-learn",
  "sqlalchemy",
  "torch",
  "transformers",
]
